
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 631869
	#The name of the modpack
	modpackName = "The Latest Summer Fun - Extremely Neat Brand New Edition (With Dairy!)"
	#The version of the modpack
	modpackVersion = "v1.0.0"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

